# Generated by Django 4.2.10 on 2024-03-04 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': (('send_private_email', 'Can send private email to user by button.'),)},
        ),
    ]
